service:
  name: bff-admin
  version: v1
env:
  mode: dev
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 60s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 60s
auth:
  service_key: "kbk_"
  api_key: "kbk_"
  api_key_expire: "86400"
data:
  redis:
    addr: 127.0.0.1:6379
    password: ""
    read_timeout: 0.2s
    write_timeout: 0.2s
    prefix: kbk_
endpoint:
  time_out: 60s
  administrator: administrator.kbk:9000
  authorization: authorization.kbk:9000
  log: kbk-log.kbk:9000
  oss: oss.kbk:9000
jwt:
  key: "kbk-admin"
  expire: 86400s
  issuer: "zhouqi"  