// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ZQCard/kbk-bff-admin/internal/conf"
	"github.com/ZQCard/kbk-bff-admin/internal/data"
	"github.com/ZQCard/kbk-bff-admin/internal/server"
	"github.com/ZQCard/kbk-bff-admin/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(env *conf.Env, confServer *conf.Server, confService *conf.Service, confData *conf.Data, bootstrap *conf.Bootstrap, auth *conf.Auth, endpoint *conf.Endpoint, logger log.Logger) (*kratos.App, func(), error) {
	client := data.NewRedisClient(confData)
	administratorServiceClient := data.NewAdministratorServiceClient(endpoint)
	authorizationServiceClient := data.NewAuthorizationServiceClient(auth, endpoint)
	logServiceClient := data.NewApiLogClient(endpoint)
	ossClient := data.NewOssClient(endpoint)
	dataData, cleanup, err := data.NewData(bootstrap, client, logger, administratorServiceClient, authorizationServiceClient, logServiceClient, ossClient)
	if err != nil {
		return nil, nil, err
	}
	administratorRepo := data.NewAdministratorRepo(dataData, logger)
	authorizationRepo := data.NewAuthorizationRepo(dataData, logger)
	apiLogRepo := data.NewApiLogRepo(dataData, logger)
	ossRepo := data.NewOssRepo(dataData, logger)
	adminInterface := service.NewAdminInterface(logger, administratorRepo, authorizationRepo, apiLogRepo, ossRepo)
	httpServer := server.NewHTTPServer(confServer, bootstrap, adminInterface, authorizationServiceClient, logger, logServiceClient, client)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
